name: Run collection, updates, prediction, evaluation script pipeline

on:
  schedule:
    - cron: '0 22 * * *'  # Run daily at Greek midnight (UTC midnight + 2 hours)
  workflow_dispatch:

jobs:
  run_pipeline:
    defaults:
      run:
        shell: bash

    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install project
        run: poetry install --no-interaction
      #----------------------------------------------
      #              run data collection
      #----------------------------------------------
      - name: Run data collection script
        run: |
          source $VENV
          python run_data_collection.py
      
      #----------------------------------------------
      #              run updates
      #----------------------------------------------
      #- name: Run updates script
      #  run: |
      #    source $VENV
      #    python run_updates.py

      #----------------------------------------------
      #              run predictions
      #----------------------------------------------
      - name: Run predictions script
        run: |
          source $VENV
          python run_predictions.py

      #----------------------------------------------
      #              run evaluation
      #----------------------------------------------
      - name: Run evaluation script
        run: |
          source $VENV
          python run_evaluation_per_season.py
