name: Run collection, updates, prediction, evaluation script pipeline

on:
  schedule:
    - cron: '0 22 * * *'  # Run daily at Greek midnight (UTC midnight + 2 hours)
  workflow_dispatch:

jobs:
  run_pipeline:
    defaults:
      run:
        shell: bash

    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: pip install -r requirements.txt

      #----------------------------------------------
      #              run data collection
      #----------------------------------------------
      - name: Run data collection script
        run: python run_data_collection.py

      #----------------------------------------------
      #              run updates
      #----------------------------------------------
      #- name: Run updates script
      #  run: python run_updates.py

      #----------------------------------------------
      #              run predictions
      #----------------------------------------------
      - name: Run predictions script
        run: python run_predictions.py

      #----------------------------------------------
      #              run evaluation
      #----------------------------------------------
      - name: Run evaluation script
        run: python run_evaluation_per_season.py